### ISSUE TITLE
OpenCV Path

### ISSUE THREAD

**Issue by danielstumpp** [ccf23/Dependability-for-Harris#1]
I don't know if the cmake configuration is path-dependent on the openCV libraries. Currently, I have the local machine openCV library compiled at /usr/local/lib and the arm statically compiled library at /usr/lib

**Comment by rom81** [comment]
It seems like it's possible to specify where cmake should look for a given library -- it should be possible to switch the location for arm/native in CMakeLists.txt, so I'll give this a shot.

**Comment by rom81** [comment]
^^ this method works, so I'm going to push a commit (soon) that fixes this.
