### ISSUE TITLE
Change setBHP() to randomly set bit_hit_prob according to a normal distribution

### ISSUE THREAD

**Issue by rom81** [ccf23/Dependability-for-Harris#10]
- Modify setBHP() method in fault injector to randomly select bit_hit_prob from a range of values
- Make it so when we set the BHP with with function, we’re setting the mean of a normal distribution of bit hit probabilities
- Choose mean so that on average, there’s some small probability (maybe only in 1/100 runs) that the ABFT error threshold (~25,000) will be exceeded

**Comment by danielstumpp** [comment]
added in the referenced commit above. closing this
