### ISSUE TITLE
Feature Selection

### ISSUE THREAD

**Issue by danielstumpp** [ccf23/Dependability-for-Harris#3]
The current way it selects features is by selecting the top X number of corners. This means that the number of features detected in an image will always be the same for the same image. This makes a comparison of the number of features detected meaningless. 

We should use some type of thresholding and also consider a better way to compare the accuracy of the features selected.

**Comment by rom81** [comment]
A few ideas:

1. Take the raw count of corners (seems to be in the range of ~500,000-~700,000 for each image)
2. Instead of just looking at feature count, maybe we can make a graph of the points and responses -- this might be a better indicator of performance than raw feature count anyway

(just suggesting these as alternatives to thresholding, although I don't think that's a bad idea)

**Comment by ccf23** [comment]
We could replace the function GetMaximaPoints with a function that gets a matrix with all the Harris Corners with and without fault injection . Find which corners were errored (through matrix subtraction and counting), and report that number.

**Comment by danielstumpp** [comment]
I added a threshold based implementation for determining the maximum points. I think this the more realistic approach but saving the not-fault injected response matrix and then comparing the number of absolute pixel response value errors across approaches could be interesting and I think would give an interesting perspective on how much errors injected in the algorithm propagate through the operations down to the results

**Comment by rom81** [comment]
Thanks for adding that -- I agree. If we have time, we can always perform the absolute pixel response value comparison separately.

**Comment by danielstumpp** [comment]
I've been thinking about this more. I think the thresholding approach we are now using is the best implementation but I think we need to improve how we compare results. 

using the number of features detected may give some insight into the affect of fault injection but in other scenarios it could be misleading. For example, a run could return the exact same number of features but their positions could all be wrong. Likewise, a run could produce 10 less features but with all the ones it did predict being correct. Presumably the first scenario would be considered better if we just consider the number of images, even though it was actually entirely wrong.

I think the best solution we can achieve in the time we have is the following:
1. save the features `pointData` vectors from each benchmark run (one per image)
1. run fault injection tests
1. for each fault injection test determine the number of false positives and missing features
    * for each point in the benchmark vector look for a point in the test vector that is within a defined window
        * if no point matches then it is a missing feature
        * features in the test vector not matched are false positives
1. store feature metrics

If there aren't any concerns about this approach or any other better suggestions I will start implementing it on a branch and then create a pull request when it's ready.

**Comment by rom81** [comment]
This is an excellent point -- this approach sounds good to me. Maybe we could write the contents of `pointData` from the benchmark run to a file so it can be stored between runs and reloaded for comparison.

**Comment by danielstumpp** [comment]
Yeah, I think that's the best way to do it. I'll add a PR with these changes in a little bit.
