### ISSUE TITLE
Duplicate Default Cases

### ISSUE THREAD

**Issue by danielstumpp** [ccf23/Dependability-for-Harris#7]
The #if ... #else ... #endif preprocessor sequence is repeated for both abft and threads (and presumably the others) so that the default operation is either run twice or could be run even if one of the FT methods is enabled. 

This should be a simple fix. I think we just need to merge them together into one condition that is #if NO_FT ... #endif

**Comment by rom81** [comment]
My first thought was just to define NO_FT as something like `#define NO_FT (!ABFT && !THREADS_ON && !CHECKPOINTING_ON && !ASSERTIONS_ON)` but this case complicates it

<img width="575" alt="Screen Shot 2020-11-28 at 12 02 17 AM" src="https://user-images.githubusercontent.com/14862654/100494162-0f8a7480-310d-11eb-9466-0c29b4d07d7a.png">

**Comment by rom81** [comment]
I suppose we could just have the computeDerivatives call inside the ABFT block

**Comment by danielstumpp** [comment]
Yeah, I don't think it's that we don't want to compute it. I think I had just left it out of the if/else and it got consumed by the threading part when we merged.
